### PR TITLE
Add manage bot cycle tool

### PR DESCRIPTION
**Pull request by mlguys**
Add `https://github.com/mlguys/manage-bot-cycles` to the community tool list.

### CODE REVIEW

**Comment by rapcmia** [comment]
PR update:
1. Clone and create local docker client image for latest development branch for testing
2. Clone `add-manage-bot-cyles` branch
3. Setup simple PMM strategy via docker build `dev1_files`
4. Copied `dev1_files` and moved to `managed-bot-cycles`
5. Modified `bots_to_run` file and added `dev1`
6. Initiate `init_and_run_bot.sh`

While running the script, it was pulling from the latest docker image `coinalpha/hummingbot`. Currently Hummingbot foundation has created a new support for docker found [here](https://hub.docker.com/r/hummingbot/hummingbot/tags)
Screenshot 2022-07-29 124201

We tried to change the `init_and_run_bot.sh` file from `coinalpha/hummingbot` to `hummingbot/hummingbot` and it created a docker instance.
Screenshot 2022-07-29 124628

Run `start.sh` however getting this error related to the latest configuration management feature on hummingbot version 1.6
Screenshot 2022-07-29 124727

We assume that the script of `init_and_run_bot.sh` should be updated using the latest `create.sh` found [here](https://github.com/hummingbot/hummingbot/blob/master/installation/docker-commands/create.sh)

**Comment by mlguys** [comment]
Thanks @rapcmia for testing it. I will work on a fix and push it soon.

**Comment by mlguys** [comment]
Hey @rapcmia, I have updated the PR and make it supports latest `development` or `dev-1.7.0` of HB client. Please be noted that `development` or `dev-1.7.0` is the only version that the `init_and_run_bot.sh` script supports, older version like 1.6.0 will not work.

**Comment by rapcmia** [comment]
Hi @mlguys thanks for the update

It seems that its now using the updated helper scripts and confirmed the missing folders are now fixed. However when I tried to run the `./init_and_run_bots.sh` and then `./start.sh` to open the docker client instance im getting a `invalid password` after the containers are recreated

https://user-images.githubusercontent.com/73840223/185154740-191e21b5-abb8-4790-a39f-6b604508080a.mp4

When I tried to use the helper scripts from the development branch from `../installation/docker-commands/start.sh` it returns the same `invalid password` and the workaround to fix it is by `docker rm xxx` and recreate using `create.sh` 

Steps to reproduce:
1. Create docker client instances from development branch
2. Copy and paste to `manage-bot-cycles`
3. Add docker client names to `bots-to-run`
4. Execute `init_and_run_bots.sh`
5. Execute `start.sh`

**Comment by fengtality** [comment]
@mlguys are you still planning to update this repo for the new configuration changes?

**Comment by mlguys** [comment]
Hey @mifeng, yes I will update this repo for the new changes. Sorry for the silent since last 2 months, I have been on break to recover from burnt out.

**Comment by mlguys** [comment]
Hey @rapcmia, sorry for not working on this for past few months.

About the `invalid password` error. Could you make sure that you have follow this step in the README.md file? My thought for `invalid password` error is that your `CONFIG_PASSWORD` has not been set properly in `init_and_run_bots.sh` file, could you verify that?

> After specifying bots in `bots_to_run` file, please set the following environment variables in `init_and_run_bots.sh`, line 48 -> 50, these configurations are required:
> 
> ```bash
>   export STRATEGY="pure_market_making" # Name of the strategy to auto run
>   export CONFIG_FILE_NAME="conf_pure_mm_$1.yml" # Name of the config file to auto run, $1 is template for the name of the bots in bots_to_run file
>   export CONFIG_PASSWORD='password' # Password to access your bot, it is for the login prompt when you first start the bot
> ```
> 
> ***ATTENTION:
> Please make sure that `CONFIG_PASSWORD` is set to your bot access password, without it the script will not be able to launch your bots properly and you will get `"invalid password"` error when trying to access the bot.***

**Comment by mlguys** [comment]
Also @rapcmia , I have added a usage checklist to make sure the script run properly.

**Review by rapcmia — APPROVED** [review]
Test performed:
- Setup docker client and simple PMM strategies 
- Copy docker files and moved to `manage-bot-cycles`
- Follow README
	- Rename `[exchange]-[token]-[qoutes]_files
	- Rename strategy conf_pure_mm_[exchange]-[token]-[qoutes]
- Add the docker folder on `bots-to-run`
- Review the env variables required for setup such as STRATEGY, CONFIG_PASSWORD and CONFIG_FILE_NAME
- Execute `init_and_run_bots.sh (changed sleep to 5s for test purposes) then run `docker ps`, all containers are ok 
- Execute start.sh command, ok 
- Execute update.sh command, ok

**Comment by rapcmia** [comment]
Hi @mlguys good day,
Apologies for the late response, would you please provide your ETH address so our team can send you the HBOT grant? Thank you

**Comment by fengtality** [comment]
We paid out this bounty last Friday already

**Pull request merged**
